# Generated by Django 3.2.5 on 2021-07-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_diaper'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaper',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='baby',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
        migrations.AlterField(
            model_name='diaper',
            name='date',
            field=models.DateField(verbose_name='changing date'),
        ),
    ]
